name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [ back-end ]
        node-version: [ 12.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm packages
        run: npm install
        working-directory: ${{ matrix.work-dir }}

      - name: Run `npm test`
        run: npm test:e2e
        working-directory: ${{ matrix.work-dir }}
        env:
          API_KEY: ${{secrets.API_KEY}}
